import { expect, test } from "bun:test";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { PtyDriver } from "../support/pty.ts";
import { withScenario } from "../support/scenario.ts";

test("PTY: paste, permission park, resize, execute and Ctrl+C restore the terminal", async () => withScenario("PTY: paste, permission park, resize, execute and Ctrl+C restore the terminal", async scenario => {
	const directory = scenario.cwd;
	await writeFile(join(directory, "file.txt"), "before");

	const pty = new PtyDriver(["tests/tui-integration/pty.fixture.ts"], { columns: 80, rows: 24, env: { ...process.env, FORGE_AGENT_PTY_DIRECTORY: directory } });
	scenario.defer(() => pty.close());
	const terminal = pty, child = pty.child;
	const waitFor = pty.waitFor.bind(pty);
	await waitFor(() => pty.text.includes("\x1b[?2004h") && pty.text.includes("Type a message"));
	await pty.send("\x1b[200~edit\n你好");
	await pty.send("\x1b[201");
	await pty.send("~");
	expect(pty.text).not.toContain("Permission: edit");
	terminal.write("\r");
	await waitFor(() => pty.text.includes("Permission: edit"));
	await pty.send("\x1b");
	expect(await readFile(join(directory, "file.txt"), "utf8")).toBe("before");
	await pty.capture();
	await pty.resizeAndCapture(40, 12);
	await pty.capture();
	terminal.write("\t\r");
	await waitFor(async () => (await readFile(join(directory, "session.jsonl"), "utf8")).includes("EDIT_COMPLETE"));
	expect(await readFile(join(directory, "file.txt"), "utf8")).toBe("after");
	await waitFor(async () => !(await pty.frameText()).includes("working"), "first turn settled");
	await pty.send("isecond\r");
	await waitFor(async () => (await pty.frameText()).includes("SLOW_RESPONSE_"), "second turn streams before cancellation");
	terminal.write("\x03");
	await waitFor(() => child.exitCode !== null);
	expect(await child.exited).toBe(0);
	expect(pty.text).toContain("\x1b[?2004l");
	expect(pty.text).toContain("\x1b[?1049l");
	const result = JSON.parse(await readFile(join(directory, "result.json"), "utf8"));
	expect(result.raw).toBe(false);
	expect(result.pending).toBe(0);
	expect(result.frames.map((frame: { columns: number; rows: number }) => [frame.columns, frame.rows])).toEqual([[80, 24], [40, 12]]);
	const records = (await readFile(join(directory, "session.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line));
	expect(records.filter((record) => record.message?.role === "user").map((record) => record.message.content)).toEqual([[{ type: "text", text: "edit\n你好" }], [{ type: "text", text: "second" }]]);
}, { timeoutMs: 26000 }), 35_000);
